import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-radial': 'none',
        'gradient-conic': 'none',
        'shg-welcome': 'none',
        'shg-primary': 'none',
        'shg-primary-hover': 'none',
        'shg-card': 'none',
        'gradient-sidebar': 'none',
        'gradient-primary': 'none',
        'gradient-sky': 'none',
        'gradient-card': 'none',
      },
      borderRadius: {
        '2xl': '16px',
        xl: '12px',
        lg: '10px',
        md: '8px',
        sm: '6px',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: '#E87545',
          foreground: '#FFFFFF',
          hover: '#D66434',
          dark: '#18233A',
        },
        secondary: {
          DEFAULT: '#38BDF8',
          foreground: '#18233A',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: '#E87545',
          foreground: '#FFFFFF',
        },
        destructive: {
          DEFAULT: '#C62828',
          foreground: '#FFFFFF',
        },
        success: {
          DEFAULT: '#087A45',
          foreground: '#FFFFFF',
        },
        warning: {
          DEFAULT: '#C94F18',
          foreground: '#FFFFFF',
        },
        'app-bg': '#E9EDF2',
        'content-bg': '#F4F6F8',
        surface: {
          DEFAULT: '#FFFFFF',
          subtle: '#F6F8FA',
          item: '#FFFFFF',
        },
        border: 'var(--border, #1f2937)',
        'border-card': '#111827',
        'border-subtle': '#1f2937',
        'border-strong': '#111827',
        input: 'var(--input, #1f2937)',
        ring: '#E87545',
        sidebar: {
          DEFAULT: '#ECE9E1',
          foreground: '#111827',
          accent: '#E87545',
          muted: '#475569',
        },
        shg: {
          page: '#F3F1EC',
          card: '#FFFFFF',
          orange: '#E87545',
          'orange-hover': '#D66434',
          'orange-light': '#FAFAF7',
          navy: '#18233A',
          'navy-dark': '#0E1422',
          'navy-light': '#283754',
          sky: '#2563EB',
          'sky-light': '#EFF6FF',
          border: '#1f2937',
          black: '#111827',
          dark: '#0F172A',
          red: '#C62828',
          'red-light': '#FEE2E2',
          green: '#087A45',
          'green-light': '#E8F5ED',
          amber: '#C94F18',
          'amber-light': '#FEF3C7',
        },
        brand: {
          orange: '#E87545',
          'orange-hover': '#D66434',
          'orange-light': '#FAFAF7',
          sky: '#2563EB',
          'sky-dark': '#1D4ED8',
          'sky-light': '#EFF6FF',
          charcoal: '#18233A',
          dark: '#0E1422',
          red: '#C62828',
          'red-light': '#FEE2E2',
          surface: '#F3F1EC',
        },
      },
      boxShadow: {
        'shg-card': 'none',
        'shg-card-hover': 'none',
        'shg-btn': 'none',
        'shg-btn-hover': 'none',
        premium: 'none',
        'premium-hover': 'none',
        'premium-lg': 'none',
        sidebar: 'none',
        glow: 'none',
        'glow-sky': 'none',
        inset: 'none',
        none: 'none',
        sm: 'none',
        DEFAULT: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
        '2xl': 'none',
        inner: 'none',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.25s ease-out',
        'fade-in-up': 'fade-in-up 0.3s ease-out',
        'slide-in-right': 'slide-in-right 0.25s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
