import React from 'react';
import {
  Modal,
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { colors, borderRadius, spacing, shadows } from '../theme/theme';
import { Button } from './Button';
import { Badge } from './Badge';

interface ReceiptModalProps {
  visible: boolean;
  receiptData: any;
  onClose: () => void;
}

export const ReceiptModal: React.FC<ReceiptModalProps> = ({
  visible,
  receiptData,
  onClose,
}) => {
  if (!receiptData) return null;

  const receiptNum = receiptData.receiptNumber || receiptData.receiptNum || 'RCP-VERIFIED';
  const issueDate = receiptData.paymentDate || receiptData.createdAt || new Date().toISOString();
  const amount = Number(receiptData.amount || 0);

  return (
    <Modal
      visible={visible}
      transparent
      animationType="slide"
      onRequestClose={onClose}
    >
      <View style={styles.overlay}>
        <View style={styles.modalCard}>
          {/* Header */}
          <View style={styles.headerBar}>
            <View>
              <Text style={styles.brandTitle}>IHMS · OFFICIAL RECEIPT</Text>
              <Text style={styles.hostelName}>
                {receiptData.hostelName || receiptData.organizationName || 'Hostel Management System'}
              </Text>
            </View>
            <View style={styles.receiptTag}>
              <Text style={styles.receiptTagText}>#{receiptNum}</Text>
            </View>
          </View>

          <ScrollView style={styles.contentScroll} showsVerticalScrollIndicator={false}>
            {/* Status Banner */}
            <View style={styles.statusBanner}>
              <Badge label="TRANSACTION VERIFIED" variant="success" />
              <Text style={styles.dateText}>
                {new Date(issueDate).toLocaleDateString('en-IN', {
                  day: 'numeric',
                  month: 'short',
                  year: 'numeric',
                })}
              </Text>
            </View>

            {/* Details Card */}
            <View style={styles.detailsBox}>
              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Student Name:</Text>
                <Text style={styles.detailValue}>{receiptData.studentName || 'Student'}</Text>
              </View>

              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Customer Code:</Text>
                <Text style={[styles.detailValue, styles.highlightCode]}>
                  {receiptData.customerCode || 'N/A'}
                </Text>
              </View>

              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Room / Bed:</Text>
                <Text style={styles.detailValue}>
                  {receiptData.roomNumber ? `Room ${receiptData.roomNumber}` : 'Room Standard'}
                  {receiptData.bedCode ? ` · Bed ${receiptData.bedCode}` : ''}
                </Text>
              </View>

              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Payment Method:</Text>
                <Text style={styles.detailValue}>{receiptData.paymentMethod || 'ONLINE'}</Text>
              </View>

              <View style={styles.detailRow}>
                <Text style={styles.detailLabel}>Transaction ID:</Text>
                <Text style={[styles.detailValue, styles.monoText]}>
                  {receiptData.transactionRef || receiptNum}
                </Text>
              </View>
            </View>

            {/* Breakdown Table */}
            <View style={styles.tableBox}>
              <View style={styles.tableHeader}>
                <Text style={styles.tableHeaderItem}>Description</Text>
                <Text style={styles.tableHeaderAmount}>Amount</Text>
              </View>
              <View style={styles.tableRow}>
                <Text style={styles.tableItemText}>
                  {receiptData.feeType || 'Hostel Accommodation Fee'}
                </Text>
                <Text style={styles.tableAmountText}>₹{amount.toLocaleString('en-IN')}</Text>
              </View>
              <View style={styles.totalRow}>
                <Text style={styles.totalLabel}>TOTAL PAID</Text>
                <Text style={styles.totalAmount}>₹{amount.toLocaleString('en-IN')}</Text>
              </View>
            </View>

            <Text style={styles.footerNote}>
              This is a cryptographically verified and recorded receipt generated by the IHMS Central Ledger.
            </Text>
          </ScrollView>

          {/* Footer Action */}
          <View style={styles.footerBar}>
            <Button title="Close Receipt" onPress={onClose} variant="primary" size="md" />
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.75)',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    backgroundColor: colors.cardBg,
    borderRadius: borderRadius.xl,
    borderWidth: 2,
    borderColor: colors.borderContainer,
    maxHeight: '85%',
    overflow: 'hidden',
    ...shadows.modal,
  },
  headerBar: {
    backgroundColor: '#18233A',
    padding: spacing.md,
    borderBottomWidth: 2,
    borderBottomColor: colors.borderContainer,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandTitle: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  hostelName: {
    color: colors.textWhite,
    fontSize: 14,
    fontWeight: '800',
  },
  receiptTag: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.sm,
  },
  receiptTagText: {
    color: colors.textWhite,
    fontSize: 10,
    fontWeight: '900',
  },
  contentScroll: {
    padding: spacing.md,
  },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
    backgroundColor: colors.subtleBg,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    borderWidth: 1.5,
    borderColor: colors.borderNormal,
  },
  dateText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  detailsBox: {
    backgroundColor: colors.subtleBg,
    borderRadius: borderRadius.md,
    borderWidth: 1.5,
    borderColor: colors.borderNormal,
    padding: spacing.md,
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  detailValue: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  highlightCode: {
    color: colors.primary,
    fontWeight: '900',
  },
  monoText: {
    fontSize: 11,
  },
  tableBox: {
    borderRadius: borderRadius.md,
    borderWidth: 1.5,
    borderColor: colors.borderNormal,
    overflow: 'hidden',
    marginBottom: spacing.md,
  },
  tableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#18233A',
    padding: spacing.sm,
  },
  tableHeaderItem: {
    color: colors.textWhite,
    fontSize: 11,
    fontWeight: '800',
  },
  tableHeaderAmount: {
    color: colors.textWhite,
    fontSize: 11,
    fontWeight: '800',
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.cardBg,
    padding: spacing.sm,
  },
  tableItemText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  tableAmountText: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.primaryLight,
    padding: spacing.sm,
    borderTopWidth: 1.5,
    borderTopColor: colors.primary,
  },
  totalLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: colors.primary,
  },
  totalAmount: {
    fontSize: 14,
    fontWeight: '900',
    color: colors.primary,
  },
  footerNote: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  footerBar: {
    padding: spacing.md,
    borderTopWidth: 1.5,
    borderTopColor: colors.borderNormal,
    backgroundColor: colors.subtleBg,
  },
});
