export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OWNER = 'OWNER',
  REGIONAL_MANAGER = 'REGIONAL_MANAGER',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  WARDEN = 'WARDEN',
  RECEPTIONIST = 'RECEPTIONIST',
  ACCOUNTANT = 'ACCOUNTANT',
  MESS_MANAGER = 'MESS_MANAGER',
  STORE_MANAGER = 'STORE_MANAGER',
  SECURITY_GUARD = 'SECURITY_GUARD',
  MAINTENANCE_STAFF = 'MAINTENANCE_STAFF',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT'
}

export enum BedStatus {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  RESERVED = 'RESERVED',
  MAINTENANCE = 'MAINTENANCE',
  BLOCKED = 'BLOCKED'
}

export enum PaymentPlan {
  ONE_TIME = 'ONE_TIME',
  MONTHLY = 'MONTHLY'
}

export enum InstallmentStatus {
  UPCOMING = 'UPCOMING',
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE'
}

export enum PaymentMethod {
  CASH = 'CASH',
  UPI = 'UPI',
  CARD = 'CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  CREDIT_CARD = 'CREDIT_CARD',
  NET_BANKING = 'NET_BANKING',
  BANK_TRANSFER = 'BANK_TRANSFER',
  ONLINE = 'ONLINE'
}

export enum PaymentStatus {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  REVERSED = 'REVERSED'
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED'
}

export enum ComplaintStatus {
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  REOPENED = 'REOPENED'
}

export enum ComplaintPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum ExpenseCategory {
  SALARY = 'SALARY',
  FOOD_PROVISIONS = 'FOOD_PROVISIONS',
  ELECTRICITY = 'ELECTRICITY',
  WATER = 'WATER',
  INTERNET = 'INTERNET',
  SECURITY = 'SECURITY',
  HOUSEKEEPING = 'HOUSEKEEPING',
  REPAIRS = 'REPAIRS',
  MAINTENANCE = 'MAINTENANCE',
  INVENTORY = 'INVENTORY',
  OTHER = 'OTHER'
}

export enum VoucherType {
  RECEIPT = 'RECEIPT',
  PAYMENT = 'PAYMENT',
  JOURNAL = 'JOURNAL',
  CONTRA = 'CONTRA'
}

export enum StudentStatus {
  ACTIVE = 'ACTIVE',
  TRANSFERRED = 'TRANSFERRED',
  ALUMNI = 'ALUMNI',
  SUSPENDED = 'SUSPENDED'
}

export enum VisitorStatus {
  EXPECTED = 'EXPECTED',
  INSIDE = 'INSIDE',
  EXITED = 'EXITED',
  REJECTED = 'REJECTED'
}
